name: build-android-libpd
on:
  workflow_dispatch:
  push:
    paths: ["**/*.c", "**/*.h", "CMakeLists.txt", ".github/workflows/build-android.yml"]

jobs:
  android-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c   # safe choice with cmake toolchain
          add-to-path: true

      - name: Configure (arm64-v8a)
        run: |
          cmake -S . -B build-android-arm64 \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-24 \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DHAVE_GLOB=0 -DHAVE_GLOB_H=0

      - name: Build
        run: cmake --build build-android-arm64 --config Release -j

      - name: Find artifact
        id: findso
        run: |
          f="$(find build-android-arm64 -name libpd.so -print -quit)"
          echo "path=$f" >> $GITHUB_OUTPUT

      - name: Upload libpd.so
        uses: actions/upload-artifact@v4
        with:
          name: libpd-android-arm64
          path: ${{ steps.findso.outputs.path }}
